---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - make build-linux

- name: publish
  image: plugins/gcr
  settings:
    registry: us.gcr.io
    repo: kbpartpicker/drone-gce
    dockerfile: Dockerfile
    tags: 
    - latest
    - ${DRONE_BRANCH//\//-}
    json_key:
      from_secret: google_credentials

trigger:
  event:
  - push